services:
  postgres:
    image: postgres:16
    container_name: rapidwork_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - rapidwork_net

networks:
  rapidwork_net:
    driver: bridge
volumes:
  pg-data:
