services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - VITE_API_BASE_URL=${PUBLIC_API_BASE_URL}
        - VITE_APP_DEBUG=${APP_DEBUG:-false}
        - VITE_NODE_ENV=${NODE_ENV:-production}
    environment:
      TZ: ${TZ}
      PORT: ${PORT}
      HOST: ${HOST}
      LOG_LEVEL: ${LOG_LEVEL}
      APP_KEY: ${APP_KEY}
      NODE_ENV: ${NODE_ENV}
      SESSION_DRIVER: ${SESSION_DRIVER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      CORS_ENABLED: ${CORS_ENABLED}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    ports:
      - '${PORT:-3333}:3333'
